version: "3"

services:
  file_service:
    build: .
    restart: always
    ports:
      - 5000:5000
    environment:
      DUMMY_TEXT: "HELLO"
    volumes:
      - ./saved_files:/usr/src/app/saved_files
